import "dart:core";

final Map<String, List<String>> mapCategories = {
  "Business and Finance": business,
  "Technology" : technology,
  "Science, Engineering, and Math": stem,
  "Education": education,
  "Health Care": healthcare,
  "Art and Design" : artDesign,
  "Communications and Media" : commsMedia,
  "Law and Criminal Justice" : lawJustice,
  "Politics/International Relations" : politics,
  "Social Services" : socialService,
  "Hospitality and Tourism" : hospitalityTourism
};

final List<String> generalPaths = [
  "Business and Finance",
  "Science, Engineering, and Math",
  "Education",
  "Health Care",
  "Technology",
  "Art and Design",
  "Communications and Media",
  "Law and Criminal Justice",
  "Politics/International Relations",
  "Social Services",
  "Hospitality and Tourism",
];

//SUBLISTS:

final List<String> business = [
  "Accounting",
  "Banking",
  "Financial planning",
  "Insurance",
  "Investment banking",
  "Management consulting",
  "Marketing",
  "Real estate",
  "Sales",
  "Stockbroker",
  "Financial analyst",
  "Human resources",
  "Insurance underwriter",
  "Investment advisor",
  "Management",
  "Market research",
  "Personal financial advisor",
  "Public relations",
  "Risk management",
  "Sales management",
  "Tax preparation",
  "Treasury management",
  "Venture capital",
  "Wealth management",
  "Credit analyst"
];

final List<String> education = [
  "Teacher",
  "Principal",
  "Superintendent",
  "Dean",
  "Professor",
  "Curriculum specialist",
  "Instructional coordinator",
  "School counselor",
  "School psychologist",
  "Speech therapist",
  "Special education teacher",
  "Educational consultant",
  "Educational researcher",
  "Librarian",
  "Reading specialist",
  "Museum educator",
  "Online instructor",
  "Private tutor",
  "Educational technologist",
  "Student affairs officer",
  "Adult education instructor",
  "Career counselor",
  "ESL teacher",
  "Early childhood educator",
  "Teacher assistant"
];

final List<String> healthcare = [
  "Doctor",
  "Nurse",
  "Dentist",
  "Pharmacist",
  "Physical therapist",
  "Occupational therapist",
  "Speech therapist",
  "Radiographer",
  "Laboratory technician",
  "Medical assistant",
  "Social worker",
  "Health educator",
  "Dietitian",
  "Mental health counselor",
  "Chiropractor",
  "Optometrist",
  "Podiatrist",
  "Athletic trainer",
  "Emergency medical technician",
  "Genetic counselor",
  "Nurse practitioner",
  "Midwife",
  "Hospice and palliative care nurse",
  "Respiratory therapist",
  "Veterinary technician"
];

final List<String> technology = [
  "Software developer",
  "Data scientist",
  "Information security analyst",
  "Network engineer",
  "Database administrator",
  "Web developer",
  "Mobile app developer",
  "Cloud engineer",
  "DevOps engineer",
  "Systems analyst",
  "Technical support specialist",
  "Quality assurance tester",
  "Technical project manager",
  "Technical writer",
  "Game developer",
  "User experience designer",
  "Virtual reality developer",
  "Artificial intelligence engineer",
  "Internet of Things (IoT) developer",
  "Robotics engineer",
  "3D artist",
  "Animator",
  "Graphic designer",
  "Technical trainer",
  "Technical recruiter"
];

final List<String> artDesign = [
  "Graphic designer",
  "Web designer",
  "Fashion designer",
  "Interior designer",
  "Illustrator",
  "Multimedia artist",
  "Photographer",
  "Fine artist",
  "Art director",
  "Art therapist",
  "Game artist",
  "Industrial designer",
  "Landscape architect",
  "Animator",
  "User experience designer",
  "Costume designer",
  "Makeup artist",
  "Set designer",
  "Technical designer",
  "Textile designer",
  "Toy designer",
  "Video game designer",
  "Visual merchandiser",
  "Creative director",
  "User interface designer"
];

final List<String> commsMedia = [
  "Public relations specialist",
  "Advertising account executive",
  "Marketing manager",
  "Event planner",
  "Social media manager",
  "Journalist",
  "News anchor",
  "Radio DJ",
  "Television producer",
  "Film director",
  "Screenwriter",
  "Actor",
  "Voiceover artist",
  "Animator",
  "Graphic designer",
  "Website developer",
  "User experience (UX) designer",
  "Technical writer",
  "Editor",
  "Translation specialist",
  "Interpreter",
  "Speechwriter",
  "Public speaking coach",
  "Corporate communications specialist",
  "Media planner"
];

final List<String> lawJustice = [
  "Attorney",
  "Judge",
  "Prosecutor",
  "Defense lawyer",
  "Paralegal",
  "Legal secretary",
  "Bailiff",
  "Court reporter",
  "Probation officer",
  "Victim advocate",
  "Police officer",
  "Detective",
  "Federal agent",
  "Border patrol agent",
  "Correctional officer",
  "Parole officer",
  "Forensic scientist",
  "Crime scene investigator",
  "Private investigator",
  "Cybersecurity analyst",
  "Fraud investigator",
  "Intelligence analyst",
  "Security officer",
  "Legal mediator",
  "Criminologist"
];

final List<String> stem = [
  "Biomedical engineer",
  "Chemical engineer",
  "Civil engineer",
  "Computer scientist",
  "Data scientist",
  "Electrical engineer",
  "Environmental engineer",
  "Geological engineer",
  "Industrial engineer",
  "Materials engineer",
  "Mechanical engineer",
  "Nuclear engineer",
  "Petroleum engineer",
  "Software engineer",
  "Agricultural scientist",
  "Astronomer",
  "Biochemist",
  "Biologist",
  "Chemist",
  "Ecologist",
  "Geologist",
  "Marine biologist",
  "Meteorologist",
  "Microbiologist",
  "Physicist"
];

final List<String> socialService = [
  "Social worker",
  "Counselor",
  "Psychologist",
  "Marriage and family therapist",
  "Mental health counselor",
  "Rehabilitation counselor",
  "School counselor",
  "Substance abuse counselor",
  "Gerontologist",
  "Health educator",
  "Case manager",
  "Community organizer",
  "Crisis counselor",
  "Human services worker",
  "Nonprofit manager",
  "Probation officer",
  "Rehabilitation specialist",
  "Substance abuse treatment coordinator",
  "Victim advocate",
  "Vocational counselor",
  "Adoption specialist",
  "Child and family therapist",
  "Elder care specialist",
  "Medical and health services manager",
  "Substance abuse counselor"
];

final List<String> hospitalityTourism = [
  "Hotel manager",
  "Restaurant manager",
  "Event planner",
  "Travel agent",
  "Tour guide",
  "Concierge",
  "Hotel receptionist",
  "Food and beverage manager",
  "Cruise ship worker",
  "Airline worker",
  "Tour operator",
  "Hospitality sales representative",
  "Event coordinator",
  "Hotel concierge",
  "Hospitality consultant",
  "Hospitality recruiter",
  "Hospitality trainer",
  "Hospitality marketer",
  "Hospitality public relations specialist",
  "Hospitality procurement specialist",
  "Hospitality financial manager",
  "Hospitality IT specialist",
  "Hospitality design specialist",
  "Hospitality sustainability specialist",
  "Hospitality human resources specialist"
];

final List<String> politics = [
  "Politician",  
  "Political strategist",  
  "Lobbyist",  
  "Political analyst",  
  "Diplomat",  
  "Foreign correspondent",  
  "Campaign manager",  
  "Public policy analyst",  
  "Public affairs specialist",
  "Government affairs specialist",  
  "Foreign service officer",  
  "Political scientist",  
  "Political campaign fundraiser",  
  "Political fundraiser",  
  "Political party organizer",  
  "Political party leader",  
  "Political communication specialist",  
  "Government relations specialist",  
  "International development worker",  
  "International humanitarian worker",  
  "International organization worker",  
  "International human rights worker",  
  "International trade specialist",  
  "International law specialist",  
  "International relations professor",  
];